import { Router } from 'express';
import crypto from 'node:crypto';
import Kit from '../models/Kit.js';
import { buildKit } from '../services/pipeline.js';
import { createKitSchema, validateKit } from '../utils/validation.js';
const r=Router(); const jobs=new Map();
const key=(jd,url)=>crypto.createHash('sha256').update(jd+'|'+url).digest('hex');
r.get('/',async(req,res)=>res.json(await Kit.find({userId:req.user.id}).sort({updatedAt:-1}).select('_id data.source data.coverage createdAt updatedAt')));
r.get('/:id',async(req,res)=>{const k=await Kit.findOne({_id:req.params.id,userId:req.user.id});if(!k)return res.status(404).json({error:'KIT_NOT_FOUND'});res.json(k);});
r.post('/generate',async(req,res)=>{try{const input=createKitSchema.parse(req.body);const hash=key(input.jd,input.company_url);const old=await Kit.findOne({userId:req.user.id,'data.source.input_hash':hash});if(old)return res.json({jobId:null,kitId:String(old._id),duplicate:true});const jobId=crypto.randomUUID();jobs.set(jobId,{status:'running',stage:'Extracting job requirements',progress:10});res.status(202).json({jobId});(async()=>{try{jobs.set(jobId,{status:'running',stage:'Researching company',progress:25});const data=await buildKit(input);data.source.input_hash=hash;jobs.set(jobId,{status:'running',stage:'Saving kit',progress:90});const saved=await Kit.create({userId:req.user.id,data});jobs.set(jobId,{status:'done',progress:100,kitId:String(saved._id)});}catch(e){jobs.set(jobId,{status:'failed',progress:100,error:e.message||'GENERATION_FAILED'});}})();}catch(e){res.status(400).json({error:e.errors||e.message});}});
r.post('/batch',async(req,res)=>{const cases=req.body?.cases;if(!Array.isArray(cases)||!cases.length)return res.status(400).json({error:'CASES_ARRAY_REQUIRED'});let started=0;for(const c of cases.slice(0,10)){if(!c?.jd||!c?.company_url||!Number.isInteger(c?.days))continue;started++;(async()=>{try{const data=await buildKit({jd:c.jd,company_url:c.company_url,days:c.days});data.source.batch_case_id=c.id||null;await Kit.create({userId:req.user.id,data});}catch(e){console.error('batch case failed',c.id,e.message);}})();}res.status(202).json({started});});
r.get('/jobs/:jobId',authJob,(req,res)=>res.json(req.job));
function authJob(req,res,next){const j=jobs.get(req.params.jobId);if(!j)return res.status(404).json({error:'JOB_NOT_FOUND'});req.job=j;next();}
r.patch('/:id',async(req,res)=>{const k=await Kit.findOne({_id:req.params.id,userId:req.user.id});if(!k)return res.status(404).json({error:'KIT_NOT_FOUND'});if(req.body.data){try{validateKit(req.body.data);k.data=req.body.data;}catch(e){return res.status(400).json({error:e.message});}}if(req.body.practice)k.practice=req.body.practice;await k.save();res.json(k);});
r.post('/:id/regenerate',async(req,res)=>{const k=await Kit.findOne({_id:req.params.id,userId:req.user.id});if(!k)return res.status(404).json({error:'KIT_NOT_FOUND'});try{const section=req.body.section;if(!['company_brief','questions','schedule'].includes(section))return res.status(400).json({error:'INVALID_SECTION'});const rebuilt=await buildKit({jd:req.body.jd||k.data.source.jd||'',company_url:k.data.source.company_url,days:k.data.schedule.days_available});const merged=structuredClone(k.data);if(section==='company_brief')merged.company_brief=rebuilt.company_brief;if(section==='questions')merged.questions=rebuilt.questions;if(section==='schedule')merged.schedule=rebuilt.schedule;validateKit(merged);k.data=merged;await k.save();res.json(k);}catch(e){res.status(500).json({error:e.message});}});
export default r;
