'use client';
import {useEffect,useState} from 'react';
import {api} from '../../../lib/api';
import Link from 'next/link';
import EditableText from '../../../components/EditableText';
import {useParams} from 'next/navigation';
const categories=['technical','behavioural','system-design','company-fit'];

export default function KitPage(){
 const {id}=useParams();const [k,setK]=useState<any>(null),[err,setErr]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{api('/kits/'+id).then(setK).catch(e=>setErr(e.message))},[id]);
 if(err)return <main className="max-w-4xl mx-auto p-8 text-red-600" role="alert">{err.replaceAll('_',' ')}</main>;
 if(!k)return <main className="max-w-4xl mx-auto p-8">Loading kit…</main>;
 const d=k.data;
 async function save(next:any,edits=k.edits||{}){setSaving(true);setErr('');try{setK({...k,data:next,edits});setK(await api('/kits/'+id,{method:'PATCH',body:JSON.stringify({data:next,edits})}));}catch(e:any){setErr(e.message);setK(k)}finally{setSaving(false)}}
 const mark=(qid:string)=>({...k.edits,questions:{...(k.edits?.questions||{}),[qid]:true}});
 function updateQuestion(i:number,key:string,value:string){const n=structuredClone(d);n.questions[i][key]=value;save(n,mark(n.questions[i].id))}
 function move(i:number,by:number){const j=i+by;if(j<0||j>=d.questions.length)return;const n=structuredClone(d);[n.questions[i],n.questions[j]]=[n.questions[j],n.questions[i]];save(n,mark(n.questions[i].id))}
 function removeQuestion(qid:string){const n=structuredClone(d);n.questions=n.questions.filter((q:any)=>q.id!==qid);n.schedule.days=n.schedule.days.map((day:any)=>({...day,question_ids:day.question_ids.filter((x:string)=>x!==qid)}));save(n,mark(qid))}
 function addQuestion(){const r=d.role.requirements[0];if(!r)return setErr('A question needs a requirement.');const n=structuredClone(d),q={id:`manual-${Date.now()}`,requirement_ids:[r.id],category:'technical',prompt:'New question — click to edit',answer_outline:'Add an answer outline',difficulty:1};n.questions.push(q);save(n,mark(q.id))}
 function updateCard(i:number,key:string,value:string){const n=structuredClone(d);n.flashcards[i][key]=value;save(n)}
 function addCard(){const r=d.role.requirements[0];if(!r)return;const n=structuredClone(d);n.flashcards.push({id:`manual-card-${Date.now()}`,front:'New flashcard — click to edit',back:'Add the answer',requirement_ids:[r.id]});save(n)}
 function removeCard(id:string){const n=structuredClone(d);n.flashcards=n.flashcards.filter((c:any)=>c.id!==id);save(n)}
 async function regenerate(section:string){setSaving(true);setErr('');try{setK(await api('/kits/'+id+'/regenerate',{method:'POST',body:JSON.stringify({section,jd:d.source.jd})}))}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
 return <main className="max-w-6xl mx-auto px-5 py-8"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-emerald-700 font-bold">{d.source.company}</p><h1 className="text-3xl font-black">{d.role.title}</h1></div><Link className="btn btn-primary" href={`/practice/${id}`}>Practice flashcards</Link></div>{err&&<p role="alert" className="card mt-4 text-red-600">{err.replaceAll('_',' ')}</p>}<p className="muted text-sm mt-3" aria-live="polite">{saving?'Saving changes…':'Changes save automatically.'}</p>
 <section className="grid lg:grid-cols-3 gap-4 mt-5"><div className="card lg:col-span-2"><div className="flex justify-between gap-3"><h2 className="text-xl font-black">Company brief</h2><button disabled={saving} className="btn btn-secondary" onClick={()=>regenerate('company_brief')}>Regenerate</button></div><div className="mt-4"><EditableText value={d.company_brief.summary} onSave={v=>{const n=structuredClone(d);n.company_brief.summary=v;save(n)}}/></div><h3 className="font-bold mt-5">What they do</h3><div className="mt-2"><EditableText value={d.company_brief.what_they_do} onSave={v=>{const n=structuredClone(d);n.company_brief.what_they_do=v;save(n)}}/></div></div><div className="card"><h2 className="text-xl font-black">Coverage</h2><p className="mt-3">{d.coverage.uncovered_requirement_ids.length?'Gaps: '+d.coverage.uncovered_requirement_ids.join(', '):'✓ All requirements covered'}</p><p className="muted mt-2">Passes: {d.coverage.passes}</p></div></section>
 <section className="card mt-4"><h2 className="text-xl font-black">Role requirements</h2><div className="space-y-3 mt-4">{d.role.requirements.map((r:any)=><div key={r.id} className="border rounded-lg p-3"><b>{r.id} · {r.priority}</b><p>{r.text}</p></div>)}</div></section>
 <section className="card mt-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">Question bank</h2><p className="muted text-sm">Edit, move, recategorise, add, or delete questions.</p></div><div className="flex gap-2"><button disabled={saving} className="btn btn-secondary" onClick={addQuestion}>+ Add question</button><button disabled={saving} className="btn btn-secondary" onClick={()=>regenerate('questions')}>Regenerate</button></div></div><div className="space-y-4 mt-4">{d.questions.map((q:any,i:number)=><div key={q.id} className="border rounded-xl p-4"><div className="flex flex-wrap justify-between gap-2"><span className="text-xs uppercase muted">{q.id} · difficulty {q.difficulty}</span><span className="flex gap-2"><button aria-label="Move question up" disabled={saving||i===0} className="btn btn-secondary py-1 px-2" onClick={()=>move(i,-1)}>↑</button><button aria-label="Move question down" disabled={saving||i===d.questions.length-1} className="btn btn-secondary py-1 px-2" onClick={()=>move(i,1)}>↓</button><button disabled={saving} className="text-red-700 underline" onClick={()=>removeQuestion(q.id)}>Delete</button></span></div><label className="block text-sm mt-3">Category <select className="border rounded p-1 ml-2" value={q.category} onChange={e=>updateQuestion(i,'category',e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div className="font-bold mt-3"><EditableText value={q.prompt} onSave={v=>updateQuestion(i,'prompt',v)}/></div><div className="mt-3 text-sm"><EditableText value={q.answer_outline} onSave={v=>updateQuestion(i,'answer_outline',v)}/></div></div>)}</div></section>
 <section className="card mt-4"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-black">Flashcards</h2><p className="muted text-sm">Click text to edit.</p></div><button disabled={saving} className="btn btn-secondary" onClick={addCard}>+ Add flashcard</button></div><div className="grid md:grid-cols-2 gap-3 mt-4">{d.flashcards.map((c:any,i:number)=><div key={c.id} className="border rounded-xl p-4"><div className="flex justify-between"><b>{c.id}</b><button disabled={saving} className="text-red-700 underline" onClick={()=>removeCard(c.id)}>Delete</button></div><div className="font-bold mt-3"><EditableText value={c.front} onSave={v=>updateCard(i,'front',v)}/></div><div className="mt-3 text-sm"><EditableText value={c.back} onSave={v=>updateCard(i,'back',v)}/></div></div>)}</div></section>
 <section className="card mt-4"><div className="flex justify-between"><h2 className="text-xl font-black">Study schedule</h2><button disabled={saving} className="btn btn-secondary" onClick={()=>regenerate('schedule')}>Regenerate</button></div><div className="grid md:grid-cols-2 gap-3 mt-4">{d.schedule.days.map((x:any)=><div key={x.day} className="border rounded-xl p-4"><b>Day {x.day}</b><p>{x.focus}</p><p className="muted">{x.minutes} min · {x.question_ids.length} questions</p></div>)}</div></section></main>
}
